//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageVirtualServers.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VirtualServer
    {
        private bool? checkedServer;
        public int VirtualServerId { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm:ss}")]
        public Nullable<System.DateTime> CreateDateTime { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm:ss}")]
        public Nullable<System.DateTime> RemoveDateTime { get; set; }
        public byte[] Seq { get; set; }
        public Nullable<bool> CheckedServer
        {
            get
            {
                return checkedServer ?? false;
            }
            set
            {
                checkedServer = value;
            }
        }

        public VirtualServer()
        {
            CheckedServer = false;
        }
    }
}
